### ISSUE TITLE
Error thrown when running "source ../env.sh; node index.js" command in tutorial step

### ISSUE THREAD

**Issue by sadzebra** [GetStream/stream-react-example#35]
When following the set up tutorial i get an error on the step for the command above "source ../env.sh; node index.js"

The error generated in the terminal is
`/github/stream-react-example/api/index.js:74
);
^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)`

To this point i run the npm install commands in both /api and /app dirs and installed the DB, i think added the db info into the env.sh as well as the getstream id, key and secret.

The error codes to this section of code
`server.use(
	jwt({ secret: config.jwt.secret }).unless({
		path: ['/users'],
	}),
);`   
 the link it refers to is the end ');'

I have no idea how to overcome this or what the problem is. If you need more information let me know?

**Comment by dwightgunning** [comment]
Looks like a syntax error introduced by some [automated linting](https://github.com/GetStream/stream-react-example/blame/d664ec314c7c9160f871fc0450d4474442db7787/api/index.js#L74).

I'll check I can reproduce it and see about a fix.

**Comment by dwightgunning** [comment]
I can replicate this error with Node versions < 8.0.

This is due to the lack of support for [trailing commas in function calls](http://node.green/#ES2017-features-trailing-commas-in-function-syntax).

Since these trailing commas now appear throughout the codebase it's not quick one-line fix. I've raised #36 to open discussion about whether this should be reverted.

@sadzebra - can you confirm the version of node you're using by running `node --version`? If it's <v8.0 then the quickest workaround will be to upgrade and I'd recommend (nvm)[https://github.com/creationix/nvm]. That being the case I'd propose to close this issue. If you still see the error after confirming Node v8.x then we should keep this issue open.

**Comment by sadzebra** [comment]
@dwightgunning, Thanks for the help.
 
I can confirm that upgrading to the latest stable (8.x) instead of the LTS version (6.x) solves this problem. However i seem to get more errors, is there a way of getting some extra support on this? 

I just get the loading screen now and it doesn't go past this.

**Comment by sadzebra** [comment]
This is solved, solution is to use version of node  v8 onward.

**Comment by dwightgunning** [comment]
@sadzebra - just to confirm you were able to work through the subsequent problem with the loading screen?

**Comment by sadzebra** [comment]
Yes, everything is up and running now on version 8.4.0 of nodes.

**Comment by dwightgunning** [comment]
Brilliant. Thanks again!
